version: 0.2
phases:
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - npx projen build
      - echo "npx typedoc --tsconfig ./tsconfig.dev.json"
artifacts:
  files:
    - docs/generated/**/*
