version: 0.2
phases:
  install:
    commands:
      - yarn
      - pip install twine
  pre_build:
    commands:
      - aws codeartifact login --tool npm --repository jsii --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}"
      - aws codeartifact login --tool twine --repository jsii --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}"
  build:
    commands:
      - npx projen release
      - echo "npx typedoc --tsconfig ./tsconfig.dev.json"
  post_build:
    commands:
      - npm publish
      - twine upload --repository codeartifact ./dist/python/*.tar.gz