version: 0.2
phases:
  install:
    commands:
      - yum install -y tree
      - yarn
      - pip install twine
  build:
    commands:
      - npx projen release
      - echo "npx typedoc --tsconfig ./tsconfig.dev.json"
  post_build:
    commands:
      - CODE_ARTIFACT_TOKEN="$(aws codeartifact get-authorization-token --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}" --query authorizationToken --output text)"
      - >-
          TWINE_USERNAME='aws'
          TWINE_PASSWORD="${CODE_ARTIFACT_TOKEN}"
          TWINE_REPOSITORY_URL="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository jsii --format pypi --query repositoryEndpoint --output text)"
          npx -p publib@latest publib-pypi
      - >-
          NPM_DIST_TAG='latest'
          NPM_REGISTRY="$(aws codeartifact get-repository-endpoint --domain "kltest${CODE_ARTIFACT_DOMAIN}" --repository jsii --format npm --query repositoryEndpoint --output text)"
          npx -p publib@latest publib-npm
      - >-
          export MAVEN_USERNAME='aws' &&
          export MAVEN_PASSWORD="${CODE_ARTIFACT_TOKEN}" &&
          export MAVEN_REPOSITORY_URL="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository jsii --format maven --query repositoryEndpoint --output text)" &&
          npx -p publib@latest publib-maven
      - aws codeartifact login --tool npm --repository jsii --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}"
      - aws codeartifact login --tool twine --repository jsii --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}"
      - aws codeartifact login --tool dotnet --repository jsii --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}"
      - tree dist
      - cat ./dist/java/com/pharrox/jsii/cdk-extensions/0.0.0/cdk-extensions-0.0.0.pom
      - npm publish
      - twine upload --repository codeartifact ./dist/python/*.tar.gz
      - dotnet nuget push ./dist/dotnet/*.nupkg -s "${CODE_ARTIFACT_DOMAIN}/jsii"