version: 0.2
phases:
  install:
    commands:
      - yarn
      - pip install git-remote-codecommit twine
      - dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
      - yum install -y tree
  pre_build:
    commands:
      - git config user.name "codecommit"
      - git config user.email "codecommit@amazonaws.com"
      - git remote add codecommit "${CODECOMMIT_GRC_URL}"
      - dotnet codeartifact-creds install
      - mv "$(which mvn)" /tmp/mvn
      - echo -e '#!/bin/bash\n/tmp/mvn "$@" | tee /tmp/mvn-log.txt' > /usr/bin/mvn
      - chmod +x /usr/bin/mvn
  build:
    commands:
      - npx projen release
      - cat /tmp/mvn-log.txt
      - npx typedoc --tsconfig ./tsconfig.dev.json
  post_build:
    commands:
      - RELEASE_TAG="$(cat dist/releasetag.txt)"
      - echo "Using release tag '${RELEASE_TAG}'"
      - git tag "${RELEASE_TAG}"
      - git push codecommit "${RELEASE_TAG}"
      - aws s3 sync ./docs/generated/ "s3://${DOCS_BUCKET}/" --only-show-errors
      - env
      - echo "${JAVA_HOME}"
      - tree dist
      - CODE_ARTIFACT_TOKEN="$(aws codeartifact get-authorization-token --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}" --query authorizationToken --output text)"
      - >-
          MAVEN_USERNAME='aws'
          MAVEN_PASSWORD="${CODE_ARTIFACT_TOKEN}"
          MAVEN_SERVER_ID='codeartifact'
          MAVEN_REPOSITORY_URL="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository "${CODE_ARTIFACT_REPO}" --format maven --query repositoryEndpoint --output text)"
          NPM_DIST_TAG='latest'
          NPM_REGISTRY="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository "${CODE_ARTIFACT_REPO}" --format npm --query repositoryEndpoint --output text | sed -r 's!^https?://!!')"
          NUGET_API_KEY="${CODE_ARTIFACT_TOKEN}"
          NUGET_SERVER="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository "${CODE_ARTIFACT_REPO}" --format nuget --query repositoryEndpoint --output text)v3/index.json"
          TWINE_USERNAME='aws'
          TWINE_PASSWORD="${CODE_ARTIFACT_TOKEN}"
          TWINE_REPOSITORY_URL="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository "${CODE_ARTIFACT_REPO}" --format pypi --query repositoryEndpoint --output text)"
          npx -p publib@latest publib
