version: 0.2
phases:
  install:
    commands:
      - yum install -y tree
      - yarn
      - pip install twine
  build:
    commands:
      - npx projen release
      - echo "npx typedoc --tsconfig ./tsconfig.dev.json"
  post_build:
    commands:
      - CODE_ARTIFACT_TOKEN="$(aws codeartifact get-authorization-token --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}" --query authorizationToken --output text)"
      - >-
          MAVEN_USERNAME='aws'
          MAVEN_PASSWORD="${CODE_ARTIFACT_TOKEN}"
          MAVEN_SERVER_ID='codeartifact'
          MAVEN_REPOSITORY_URL="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository jsii --format maven --query repositoryEndpoint --output text)"
          npx -p publib@latest publib-maven
      - >-
          TWINE_USERNAME='aws'
          TWINE_PASSWORD="${CODE_ARTIFACT_TOKEN}"
          TWINE_REPOSITORY_URL="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository jsii --format pypi --query repositoryEndpoint --output text)"
          npx -p publib@latest publib-pypi
      - >-
          NUGET_API_KEY="${CODE_ARTIFACT_TOKEN}"
          NUGET_SERVER="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository jsii --format nuget --query repositoryEndpoint --output text)v3/index.json"
          npx -p publib@latest publib-nuget
      - >-
          NPM_DIST_TAG='latest'
          NPM_REGISTRY="$(aws codeartifact get-repository-endpoint --domain "${CODE_ARTIFACT_DOMAIN}" --repository jsii --format npm --query repositoryEndpoint --output text)"
          npx -p publib@latest publib-npm
