version: 0.2
phases:
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - npx projen build
      - echo "npx typedoc --tsconfig ./tsconfig.dev.json"
  post_build:
    commands:
      - aws codeartifact login --tool npm --repository jsii --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}"
      - npm publish
