version: 0.2
phases:
  install:
    commands:
      - yum install -y tree
      - yarn
      - pip install twine
  build:
    commands:
      - npx projen release
      - echo "npx typedoc --tsconfig ./tsconfig.dev.json"
  post_build:
    commands:
      - aws codeartifact login --tool npm --repository jsii --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}"
      - aws codeartifact login --tool twine --repository jsii --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}"
      - aws codeartifact login --tool dotnet --repository jsii --domain "${CODE_ARTIFACT_DOMAIN}" --domain-owner "${CODE_ARTIFACT_OWNER}"
      - tree dist
      - cat ./dist/java/com/pharrox/jsii/cdk-extensions/0.0.0/cdk-extensions-0.0.0.pom
      - npm publish
      - twine upload --repository codeartifact ./dist/python/*.tar.gz
      - dotnet nuget push ./dist/dotnet/*.nupkg -s "${CODE_ARTIFACT_DOMAIN}/jsii"
      - npx -p publib@latest publib-maven